# Theme Check конфигурация
root: .

# jet_cart.js и jet_cart.css са в assets/ – изключваме MissingAsset за този проект,
# защото проверката понякога не вижда файловете (кеш/контекст). Може да включите отново:
# MissingAsset:
#   enabled: true
MissingAsset:
  enabled: false
